### ISSUE TITLE
网盘链接里的PHPStudy带病毒

### ISSUE THREAD

**Issue by testnet0** [wangai3176/webug4.0#7]
网盘里的PHPStudy版本带有病毒，麻烦更新或者删除

**Comment by wangai666** [comment]
感谢提醒， 网盘中的phpstudy已删除，但是虚拟机里面装机的是一个版本 应该也存在该问题， 需要各位自己注意一下了。
另外说明下，webug是建议各位装在本地虚拟机中，并不建议装在公网，所以影响并不是很大，如果说有人放在公网上，其实没有phpstudy这个后门，一样可以搞定公网服务器。
